sudo: required
language: java
jdk: oraclejdk8
services:
  - docker

script:
  - ./mvnw clean install -B

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export TAG=if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH;fi
  - export IMAGE_NAME=$DOCKER_USER/ausecourseback
  - echo $IMAGE_NAME:$COMMIT
  - docker build -t $IMAGE_NAME:$TRAVIS_COMMIT .
  - docker tag $IMAGE_NAME:$TRAVIS_COMMIT $IMAGE_NAME:$TAG
  - docker push $IMAGE_NAME

deploy:
  provider: heroku
api_key:
  secure: 64ad335d-ff42-44ce-9c7e-67bc17c61ebe
app: ausecourseback
